### PR TITLE
Add python 3 support

### PR DESCRIPTION
**Pull request by nvbn**
Just changed iteritems to items and add decode.

### CODE REVIEW

**Comment by nikolas** [comment]
Is this ready to merge?

**Comment by gone** [comment]
Can we merge this sucker?

**Comment by nikolas** [comment]
@nvbn can you rebase to master?

**Comment by nikolas** [comment]
There was a similar pull request here that has been merged: https://github.com/dobarkod/django-casper/pull/17/files

If there's further fixes on master required for python 3, please open a new PR.

**Pull request closed without merging**
